clients/common/src/api/get-slots/index.ts, clients/common/src/api/get-slots/types.ts, clients/common/tests/api/getSlots.test.ts, clients/scheduler/package.json, clients/scheduler/src/components/time-slot-select/index.tsx, clients/scheduler/src/hooks/app-context.tsx, clients/scheduler/src/index.tsx, clients/scheduler/src/utils/types.ts
@trlehmbecker I made this PR to enable me to give a review
=> Feature: Store/Cache TimeSlots

clients/appointments/package.json, clients/scheduler/package.json
Forgot to update the appointments and scheduler nested dependency for `embed-common` to `0.0.10`. This fixes that.
=> Bump nested embed-common dep to 0.0.10

clients/scheduler/CHANGELOG.md, clients/scheduler/package.json
Release embed-scheduler v0.0.12
=> Scheduler v0.0.12

clients/scheduler/src/App.tsx, clients/scheduler/src/components/date-select/calendar/index.tsx, clients/scheduler/src/components/date-select/calendar/ui.tsx, clients/scheduler/src/components/date-select/index.tsx, clients/scheduler/src/components/time-slot-select/index.tsx, clients/scheduler/src/components/time-slot-select/ui.tsx, clients/scheduler/src/utils/dates/calendar.ts
Disable dates that don't have any available appointment slots
=> Disable calendar dates with no available slots

clients/scheduler/CHANGELOG.md, clients/scheduler/package.json
Release embed-scheduler v0.0.14
=> Scheduler v0.0.14

clients/appointments/src/utils/types.ts, clients/appointments/webpack.config.js, clients/common/src/utils/types/index.ts, clients/scheduler/src/components/date-select/calendar/index.tsx, clients/scheduler/src/components/date-select/index.tsx, clients/scheduler/src/components/time-slot-select/confirm-appointment.tsx, clients/scheduler/src/components/time-slot-select/index.tsx, clients/scheduler/src/components/time-slot-select/time-slots.tsx, clients/scheduler/src/hooks/app-context.tsx, clients/scheduler/src/index.tsx, clients/scheduler/src/utils/types.ts, clients/scheduler/webpack.config.js, clients/yarn.lock, proxy/Gemfile
- Added callback type
- Added callbacks param to Scheduler interface
- Applied callbacks within app context and various components
- [ACAI-1086 on Jira](https://modern-age.atlassian.net/browse/ACAI-1086)
- Run `npm run start --workspace=@canvas-medical/embed-common --workspace=@canvas-medical/embed-scheduler` in the `clients` folder
- Update the `scheduler/src/index.html` file to send a `callbacks` prop into the Scheduler init:
- `var callbacks = {
onBookingConfirmed: (e) => {
console.log("onBookingConfirmed", e)
},
onBookingError: (e) => {
console.log("onBookingError", e)
},
onBookingTimeSlotSelected: (e) => {
console.log("onBookingTimeSlotSelected")
},
onBookingCanceled: (e) => {
console.log("onBookingCanceled")
},
onBookingDateChange: (e) => {  
console.log("onBookingDateChange", e)
} …
=> ACAI-1086 - Added Callbacks 

clients/scheduler/CHANGELOG.md, clients/scheduler/package.json, clients/scheduler/src/index.html
Updated changelog, sample code in index.html
=> Updated scheduler to v0.0.15

clients/scheduler/CHANGELOG.md, clients/scheduler/package.json
=> test version bump

clients/scheduler/src/components/time-slot-select/index.tsx, clients/scheduler/src/components/time-slot-select/ui.tsx, clients/scheduler/src/hooks/app-context.tsx, clients/scheduler/src/hooks/index.ts, clients/scheduler/src/hooks/use-previous-value.tsx, clients/scheduler/src/index.html, clients/scheduler/src/utils/functions.ts, clients/scheduler/src/utils/types.ts
-Adds callback for the date changed event in the scheduler embed
=> ACAI-1165: Add callback for date changed event

clients/appointments/package.json, clients/common/package.json, clients/scheduler/package.json
Bumping version for all 3 packages
=> Package bump for onload refactor

clients/appointments/package.json, clients/scheduler/package.json
Enables the clients to run as expected in local dev environmnet
=> Updated version of 'common' in scheduler, appointments

clients/scheduler/CHANGELOG.md, clients/scheduler/package.json
Release scheduler v0.1.10
typo fixes for months
=> Bump scheduler version to 0.1.10

clients/common/CHANGELOG.md, clients/common/package.json
=> CHIA-161b: version bump common

clients/appointments/package.json, clients/appointments/src/components/index.tsx, clients/appointments/src/components/ui.tsx
- added dependencies :`ics` & `date-and-time` 
- appointments logic for creating `ics` file when add to calendar button clicked
=> CHIA-161c: add to calendar ics appointments tab

clients/appointments/src/components/index.tsx, clients/appointments/src/components/ui.tsx
- update appointment duration in minutes (was previously incorrect if appointment was over one hour)
- add appointment location title/address to ui
=> CHIA-161d: ics link my account appointments tab

clients/appointments/CHANGELOG.md, clients/appointments/package.json
bump appointments version 0.1.6 -> 0.1.7
=> CHIA-161e: ics link my account appointments tab

clients/appointments/src/components/ui.tsx
update appointment address to be `<a>` tag with `href` to google maps link
=> CHIA-161f: ics link my account appointments tab

clients/appointments/CHANGELOG.md, clients/appointments/package.json
=> appointments version bump 0.1.8

clients/common/src/utils/types/index.ts
update `AppointmentType` to include `patient` - common
=> CHIA-161g: ics link my account appointments tab

clients/common/CHANGELOG.md, clients/common/package.json
=> version bump common -> 0.1.6

clients/appointments/src/components/index.tsx
- default attendee name/email to appease ics
=> CHIA-161h: ics link my account appointments

clients/appointments/CHANGELOG.md, clients/appointments/package.json
=> appointments version bump -> 0.1.9

clients/appointments/src/App.tsx, clients/appointments/src/components/index.tsx, clients/appointments/src/components/ui.tsx, clients/appointments/src/index.html, clients/appointments/src/index.tsx, clients/appointments/src/utils/functions.ts, clients/appointments/src/utils/types.ts, clients/common/src/api/get-appointments-list/index.ts
Use locationId's from Appointment response and use a dymanic location config (coming from Jade)
=> Hotfix: Support dynamic location ID's (+ dynamic location config)
